# Generated by Django 4.2.7 on 2026-02-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('area', models.FloatField(blank=True, null=True)),
                ('layout', models.CharField(blank=True, default='', max_length=50)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['region'], name='spider_hous_region_261650_idx'), models.Index(fields=['source'], name='spider_hous_source_aaca8e_idx')],
            },
        ),
    ]
