# Generated by Django 4.2.7 on 2026-02-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': '估价记录', 'verbose_name_plural': '估价记录'},
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='基础估价'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='building_age',
            field=models.IntegerField(default=0, verbose_name='房龄'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='decoration',
            field=models.CharField(choices=[('rough', '毛坯'), ('simple', '简装'), ('exquisite', '精装')], default='simple', max_length=10, verbose_name='装修'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='floor_type',
            field=models.CharField(choices=[('low', '低楼层'), ('mid', '中楼层'), ('high', '高楼层')], default='mid', max_length=10, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='has_subway',
            field=models.BooleanField(default=False, verbose_name='近地铁'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='is_school_district',
            field=models.BooleanField(default=False, verbose_name='学区房'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='orientation',
            field=models.CharField(choices=[('east', '东'), ('west', '西'), ('north', '北'), ('south', '南')], default='south', max_length=10, verbose_name='朝向'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='price_range_high',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='估价上限'),
        ),
        migrations.AddField(
            model_name='estimationhistory',
            name='price_range_low',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='估价下限'),
        ),
        migrations.AlterField(
            model_name='estimationhistory',
            name='area',
            field=models.FloatField(verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='estimationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='查询时间'),
        ),
        migrations.AlterField(
            model_name='estimationhistory',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='最终估价'),
        ),
        migrations.AlterField(
            model_name='estimationhistory',
            name='layout',
            field=models.CharField(max_length=50, verbose_name='户型'),
        ),
        migrations.AlterField(
            model_name='estimationhistory',
            name='region',
            field=models.CharField(max_length=100, verbose_name='区域'),
        ),
    ]
